### ISSUE TITLE
Suggested updates:

### ISSUE THREAD

**Issue by JPRichings** [EPCCed/dirac-docs#1]
1. Connecting to Tursa: 
    - Command line terminal: This is minor but the discussion about macOS is mixed into the Linux terminal discussion is it better separated?
    - SSH key pairs: Is the example ssh-keygen command strong enough or do we have to go to non-rsa protocols now?
2. Data Management and Transfer:
    - Archiving and data transfer: "The Tursa /work file" should be "The Tursa /home file"
3. Software Environment:
    - Update picture or "code region in mark down to latest modules on the system.
4. Running Jobs on Tursa:
    - Example Job Submission script: Remove the specific `application=./grid`  and `options=" --grid @grid@ --mpi @mpi@ --shm 2048 --shm-hugepages --accelerator-threads ${ACC_THREADS} --comms-overlap --decomposition --log Error,Warning,Message"` and replace with non grid specific text e.g. `application=XXX` and `options="YYY"`

**Comment by aturner-epcc** [comment]
@JPRichings Thanks for these. I have addressed them in an upcoming commit. My understanding of key algorithms is that the differences between RSA and other formats is not really secureness but, rather, that other algorithms offer more security for the same key size (so it is really an efficiency of key size issue). RSA 2048 is fine but a different algorithm may give the same level of security for a smaller key size. I have left this as RSA 2048 for now as I think this is secure enough.
